# Generated by Django 4.1.1 on 2022-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contact_body_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': 'information'},
        ),
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='information',
            name='instagram',
            field=models.CharField(max_length=50, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='information',
            name='linkedin',
            field=models.CharField(max_length=50, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
    ]
