# Generated by Django 4.1.1 on 2022-09-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='view',
            new_name='views',
        ),
    ]
