# Generated by Django 4.1.1 on 2022-09-25 17:29

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_view_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/blogs', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='view'),
        ),
    ]
