# Generated by Django 4.1.1 on 2022-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
