# Generated by Django 4.1.1 on 2022-09-25 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
